baseURL = 'http://viggy783.github.io/baderzone.github.io/'
languageCode = 'en-us'
title = 'Bader Lab'
theme = "ananke"

sectionPagesMenu = "main"

[params]
    body_classes = "georgia bg-near-white"
    copyright = "2022 Bader Lab"
